### ISSUE TITLE
TypeError: Logger provided is not an instance of bunyan

### ISSUE THREAD

**Issue by adomenech73** [yantrashala/loopback-component-logger#12]
I tried to add loopback-component-logger to a loopback api project.
- First I installed:

```
npm install --save loopback-component-logger bunyan
```
- Then I added to my server.js

```
var bunyan = require('bunyan');
var rootLogger = bunyan.createLogger({name: 'myAPI', level: 'info'});
var logger = require('loopback-component-logger')(rootLogger);
```
- Finally added this to component-config.json

```
,
  "loopback-component-logger": {
      "enableAPI" : true
  }
```

And I get the error pointed on execution
- Versions I'm using

```
node v6.1.0
npm 3.7.5
loopback 2.22.0
bunyan 1.8.1
loopback-component-logger 0.3.2
```
- When I comment server.js logger definition lines I get this output

```
WARN: Logger not initialized correctly  using defaultLogger
Updating level for logger with name perfLogger , New level is 30
```

I can see how defaultLogger is loaded correctly so I supose the problem must be on the Logger definition I'm using

**Comment by pbhadauria2000** [comment]
Thanks @adomenech73 for raising this issue. The initialization that you are doing looks correct. I see you are using bunyan 1.8.1. I need to check the code with the latest version. Will check today.

**Comment by adomenech73** [comment]
I've seen you commit PR #15 allready I check during this afternoon and give you feedback about

**Comment by pbhadauria2000** [comment]
@adomenech73 , I believe as this code used a specific version of bunyan - 1.5.1 and your code used 1.8.1, there was version conflict. I tried on node 6.3.1 and npm 3.9.3 and got dependency error, so not sure how you got the TypeError from the code. But the fix should resolve the issue for you.

**Comment by adomenech73** [comment]
It's just perfect!! Thanks really helpful

```
LoopBack server listening @ https://0.0.0.0:3000/
Updating level for logger with name root , New level is 30
Updating level for logger with name perfLogger , New level is 30
```
